version: '3'
services:
  app:
    image: .
    volumes:
      - ./init.sh:/app/init.sh
      - ./db/seeds.rb:/app/db/seeds.rb
      - ./tmp/pids:/app/tmp/pids
    #   - .:/app
    #   - bundle:/usr/local/bundle
    #   - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:decidim@db/decidim_staging
      - SECRET_KEY_BASE=b0ada19c892e3b02434b0a4ae28fc6482d4a98fcbda1f80d3340982f358a3c1cbab0b8e6a1f45706010517c117416a4e6c47e6c2973c1f39633e6906bb8da27e
      - DECIDIM_FORCE_SSL=false
      - QUEUE_ADAPTER=sidekiq
      - REDIS_URL=redis://redis:6379/1
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: /app/init.sh
  sidekiq:
    image: .
    volumes:
      - ./init.sh:/app/init.sh
    #   - .:/app
    #   - bundle:/usr/local/bundle
    #   - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:decidim@db/decidim_staging
      - SECRET_KEY_BASE=b0ada19c892e3b02434b0a4ae28fc6482d4a98fcbda1f80d3340982f358a3c1cbab0b8e6a1f45706010517c117416a4e6c47e6c2973c1f39633e6906bb8da27e
      - DECIDIM_FORCE_SSL=false
      - QUEUE_ADAPTER=sidekiq
      - REDIS_URL=redis://redis:6379/1
      - RUN_RAILS=false
      - RUN_SIDEKIQ=true
    depends_on:
      - redis
    command: /app/init.sh
  db:
    image: postgres:13
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=decidim
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
  # bundle:
  # node_modules:
