open_data_job:
  cron: "3 3 * * *"
  class: "InvokeRakeTaskJob"
  queue: default
  args:
    task: decidim:open_data:export

clean_data_portability_job:
  cron: "33 3 * * *"
  class: "InvokeRakeTaskJob"
  queue: default
  args:
    task: decidim:delete_data_portability_files

metrics_job:
  cron: "30 1 * * *"
  class: "InvokeRakeTaskJob"
  queue: metrics
  args:
    task: decidim:metrics:all